### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#10]
This could be good for Cascadia:

https://github.com/lincolnloop/salmon/blob/master/salmon/static/favicon.ico

But I am not sure if it's cool to use it, and if I just swap out the image that is in the public folder or what

**Comment by edwardsharp** [comment]
@Brian393 perhaps the license of that repo would help you decide if you can use it or not: https://github.com/lincolnloop/salmon/blob/master/LICENSE 

and yeah, just need to swap out the file in the public/ dir. i'll leave this issue up to you.

**Comment by richardbmx** [comment]
@Brian393  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new Favicon for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by edwardsharp** [comment]
@Brian393 closing this, can you move this issue to your repo?
