### ISSUE TITLE
Centering and size of sub-sub-menus

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#11]
They should be centered at the bottom, and also, the buttons should be a little smaller yet than the ones on the left-hand panel, so the hierarchy is visible: big buttons on the top, smaller at bottom left, and smallest along the bottm axis.

**Comment by edwardsharp** [comment]
ugh, just noticed the fix i did for this makes things to the left & right of the sub nav unable to be clicked. need to refactor this.
