### ISSUE TITLE
Scale bar

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#13]
The scale should appear at bottom center, and ONLY when the sidebar and the submenus have been collapsed. The centering is easy but how to add it to the collapse function?

**Comment by edwardsharp** [comment]
@Brian393 does this also mean you want to position the sub nav closer to the bottom of the window?

**Comment by Brian393** [comment]
Well, yes, both subnav and sub-subnavs can go about 25 pixels above the
bottom, and once I know the settings I can play around.
