### ISSUE TITLE
Scrollbars on the popups

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#16]
Although I understand that they serve a function, I think it would be worth investing some time in finding a way to avoid having those scrollbars that alter the very clean shape that popups have on most maps. On way to do this might be through css: make everything except the bar itself the same exact white as the background, so that the bar only appears when it is needed and the rest if invisible. Of course I don't know if it would work. Another way could be to have a listener that notes the sizes of the screen, and only applies the bars when they are needed (which if I understand is when the screen is small). I have seen this approach taken for other aspects of responsive design.

I find this important because the busy little bar with its arrows spilling over the boundary of the popup is very distracting, and everything else is so elegant!

**Comment by edwardsharp** [comment]
@Brian393 well, FWIW you are using a pretty marginalized browser, FF in linux; and this browser's default is to not auto-hide scroll bars. most other browsers auto-hide scroll bars... 

there's probably some CSS to fix that, i'll try to dig it up.

**Comment by Brian393** [comment]
Since you mentioned that you use Chrome I have been doing so too, but
Chrome in Linux is probably also marginal! I will try to look on a
Macintosh and see what I can see. With Chrome on Linux the issue is
actually worse! (see screenshot).

But programming for multiple browsers and responsiveness, etc, is so
difficult, whew.... If it's only on Linux then no big deal, give me some
time to check that out.

**Comment by edwardsharp** [comment]
@Brian393 i can't see the screenshot. i don't think you can attach files in email response. can you re-upload screenshot via https://github.com/edwardsharp/ecotopia-today/issues/16

**Comment by Brian393** [comment]
Here we go, sorry, always learning
![screenshot from 2018-08-20 19-29-24](https://user-images.githubusercontent.com/17584446/44374170-97a35d80-a4b2-11e8-9ca5-171956f17464.png)

**Comment by edwardsharp** [comment]
@Brian393 ah yes, i think we probably need to use `overflow: auto` instead of `overflow: scroll` CSS throughout. if it's not hard, can you try out switching these CSS rules using chrome dev tools to confirm it works?

**Comment by Brian393** [comment]
I can try a global replacement in Atom, I will do it but on a new branch!
Will take a couple minutes to get there.

I have definitely seen overflow:auto before, I think you are right

**Comment by edwardsharp** [comment]
@Brian393 oops, nope, a global search/replace is not what i'm looking for. 

can you please just try out making changes using the chrome developer tools (you can right click and select "inspect" or use the toolbar menu "View" -> developer tools. then you can just live-edit the CSS on one of these elements that has a scrollbar showing to see if changing `overflow: scroll` to `overflow:auto` will hide the scroll bars.

**Comment by Brian393** [comment]
Oh, right, got it.

I tried it and it makes a big improvement on everything, the popups, the
submenu panel, the hamburger thing when you collapse the sidebar, it's much
better everywhere

**Comment by edwardsharp** [comment]
@Brian393 fantastic; ty!
