### ISSUE TITLE
Sidebar link that can pan and zoom map

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#19]
Another thing I always wanted was a kind of hyperlink in the sidebar that would apply a new centerpoint/ resolution pair to the map view that we're looking at. So I could write. "And at location x (click *here*) you can check out situation y," and the user would be centered over and zoomed into location x on a single click, and then I would talk about situation y and maybe they could get interested and want to go there or whatever. So eally, this would be yet another sub-sub-submenu, only I would not be wanting to change anything except centerpoint/resolution, and it would be triggered from with the html text by a hyperlink.

If it sounds doable and not a headache, feel free to do it! I would love it.

**Comment by edwardsharp** [comment]
@Brian393 see WatershedIntroduction.vue or the README for ref: https://github.com/edwardsharp/ecotopia-today#links-to-re-position-map
