### ISSUE TITLE
Animation for DamsTransformation

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#21]
Main points:

--The idea is to see the dams fall onto the map one by one according to date, maybe along an arc from the left side. The map remains static; the name and date of the dams flashes up briefly over the icon, in white frosty letters with transparent background, name small, date big. Then immediately, another one falls in. I think the name/date would look good directly over the icon, covering it for just 1 or 1.5 seconds.

--When the animated sequence is over, those geojsons disappear and more complete copies of the geojsons replace them, with normal popups. An additional geojson (Aluminum.geojson) appears simultaneously, and eventually maybe another one. So there would have to a destroy event at the end of the animated sequence, and then the static layer group would be activated.

--A click anywhere on the screen should stop the animation and activate the static layer group, so the user who has already watched the sequence does not have to waste their time.

*******

In order to make this easier I have created second copies of the three dam geojsons (Bureau2, geojson, ArmyCorps2.geojson, OtherDams.geojson). These files have only two properties: "key2" is the name, and "date" is the date. I think you are going to want to change "key2" to something specific (in the prototype, I used "key2" to indicate a certain kind of popup styled in a certain fashion). You may also want to put all these in one file. However, then the different icons will also have to be handled by the geojson, which is totally possible, just add another property.

Using these second copies to trigger the animation will also allow us to edit some of the dams out, because to show them all would take too long and people would get bored. Also some of them would appear outside the viewport, and I would rather the map just remain stable and not pan around or anything. But it might be interesting to work with the full files first, and see what they do.

This is my idea, but it might not be realizable. Or it might look terrible, because it's too slow or because the animation is dodgy or whatever. So you can also invent something better. I am sure you get what I want, which is for people to have a sense of the gradual industrialization of the river system.

A real lot was done around the late 60s/early 70s. It might be cool to have all the dams that were completed in a single year appear at the same time. That way we would get a sense of these bursts of activity. I might put the aluminum plants in there too: a whole bunch get built in 1940/51, as you can imagine, for making warplanes with the hydroelectricity....

Gif shows a rough idea... looking at it, I guess it would be even better if the Army Corps came in from the left, the Bureaus from above and the Others from the right! But that might get complicated...

By the way, to be clear, the icon would stay after the text disappears, then you see a new icon that stays after the text disappears, etc, so the icons build up as the animation goes on.

![rough_idea](https://user-images.githubusercontent.com/17584446/44425421-704f9d80-a551-11e8-8e03-475c2b765fd5.gif)

**Comment by edwardsharp** [comment]
@Brian393 okay, so i've got a prototype of this working, see: https://edwardsharp.github.io/ecotopia-today/#/watershed/dams/transformation

todo:  
- [ ] the fly-in is stumping me a little bit, so it's not implemented yet. 
- [x] a click to cancel the animation (& show everything) is not implemented yet.
- [x] the dates are not in chronological order, the .geojson files just need their `features` array re-ordered
- [x] i'm not sure what order you want these to appear, currently they are in the order they are specified in `watershedDamsTransformationLayers`: Aluminum, OtherDams2, Bureau2, ArmyCorps2. if you want to change that order we'll need to change the `offsetMSec` constant which is just the length of items in the array * 1000 (given 1 second for each item). 

EDIT: also, i backed up the perspective (resolution: 3500) so you can see all the features loading. there's probably a function to tell if a feature point is in the current perspective view or not. let me know if you want me to dig into that or if the bigger resolution is fine. 

um, how did you make that .gif? did you use code ...or?

**Comment by Brian393** [comment]
Cool, this is a great start.

I suspect that to make it work chronologically would require a single
geojson file containing all the elements that are now split up into four. I
guess the geojson would have to be in chronological order (unless there is
some way to programmatically put it in chronological order). And then most
crucially, it would need a property in the geojson that says which marker
to apply, because otherwise all the objects would have the same marker and
that would not communicate an important part of the information.

I know it is possible to control the icon from a property in the geojson
but I can't do it myself.

The gif was just made manually, nothing programmatic. However there is an
ol animation function:

https://openlayers.org/en/latest/examples/feature-move-animation.html

I am sure you could animate the marker along a path of preset points, but I
suspect you could animate it with a function that creates an arc based on,
say, eight points, starting from a predetermined beginning point (always
the same) to whatever the end point is (the actual location on the map).
That would already produce a variety of curves, and it could be perfect.
Going further, you could probably use an array of origin points that would
make it seems more random and alive, so that the markers would be falling
in from different places (could be four different places, corresponding to
the four categories of markers).

This could be too difficult or two clumsy because of poor performance of
the animation function in the library, If so, the minimum solution would be
something like what you already have, but in a strict chronological order,
for example: ACdam 1936, BRdam 1937, Aluminum plant 1940, OtherDam 1941,
etc. In that case the visual animation would come from the four different
markers plus the changing titles and dates.

As I mentioned, to make it work really nicely, there would have to be a
point at the end where all the markers are destroyed and replaced by a
distinct set of four geojsons, with popups that would be more complete
(pictures, information etc). Or you would use the same geojsons, but with a
different listener that triggers different properties.

I am adding this to the issue so that its easy to find tomorrow!

I will also try to produce a single geojson with all fo0ur elements in
chronological order.

**Comment by edwardsharp** [comment]
@Brian393 

okay, implemented a click to cancel the animation (& show everything (&& you can re-start the animation by click on the nav link!!)). try it out: https://edwardsharp.github.io/ecotopia-today/#/watershed/dams/transformation

i mean, sure one .geojson would work. i thought you wanted to show each group sequentially? in which case it's as simple as i mentioned: just need to sort the features arrays chronologically. 
-or-
let me know when you create a single .geojson file that's sorted chronologically. you can add a key to the features array to reference the icon file url (like 'icons/stop.png' or whatever). also note you need an "id" key with an integer value that increments from 0. 

ALSO: if you want the popup for these features to have more details (pictures, information etc) then you need to add that data to these .geojson files...

still not totally sure about the fly-in animation feasibility, will dig in more tmrrw. however, at the moment, i think it's looking pretty good!

**Comment by edwardsharp** [comment]
@Brian393 also, just came to mind: you could keep the individual .geojson files but add a key with a value that's an offset in milliseconds that the particular feature will show. currently i'm programmatically calculating this based on the features "id" property + how many have came before it.

or perhaps even more simply, if **you just set the "id" properties across all the files in chronological order, 0-50**. make sense?

**Comment by Brian393** [comment]
Hmmm, I think I have done what I can, losing any energy....

I have a single file with two values: date and key2 (which is name)

I could not make the file itself chronological but that should be
achievable programatically with js, for example see this discussion:

https://stackoverflow.com/questions/3859239/sort-json-by-date

I think the above must be obvious to you, sorry, just to be sure. There
were many such discussions.

Any further value you would like to add to the json, just pop it in with an
editor.

I hope this helps. I gotta travel tomorrow so can't do any more!

But thanks and have a good weekend, Brian

**Comment by edwardsharp** [comment]
@Brian393 sure, could .map to sort by date but we really don't need to calculate that when we can control the data and set a static order. 

i'll edit the .geojson files in that case. have a great trip!

**Comment by edwardsharp** [comment]
@Brian393 okay, sorted the .geojson files (wrote a little utility script, see README & 
f2abb83) to be in chronological order. 

i added a black background to make the text a little more readable; not sure if you want to keep that.

- [x] there's an issue with text sometimes getting covered up by a previously placed icon. i think if there was a single .geojson layer and the features were ordered correctly in the file then openlayers would interpret that and layer correctly... (i fiddled with the `zIndex` property but that didn't make a difference)

edit/note: http://dev.openlayers.org/examples/ordering.html

**Comment by edwardsharp** [comment]
@Brian393 sending this over to you for review. let me know if you want me to keep working on this...
