### ISSUE TITLE
Mapseed Application

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#23]
The idea is to set up an application called [Mapseed](https://www.mapseed.org/). There are some good examples of it, in particular [here](https://heyduwamish.org/) and [here](https://pboakland.org/page/about) and [here](https://pugetsound.mapseed.org/page/stories). I knew about it for a while, but because you were so patient to teach me about git, I was suddenly able to download it and modify it a little and use "npm start" to see the results. I started modifying the "willamette flavor" and that modification is currently on my repo (platform, master branch). I also contacted the developers and hope to meet them when I am out in Portland. They will be able to help me with lots of things, but it was clear from our exchange that to get the full power of the application you have to host and administer it yourself.

What I would like to do  now is learn how to get the application online and how to hook it up to a backend api which they also provide. Apparently the app itself is a static build compiled with npm. The api requires a server with root access. More precisely I was told this:

"There's a separate backend codebase (https://github.com/mapseed/api) that has its own hosting-- this supports the user uploads. For the frontend hosting, we basically push everything in the www folder to an S3 bucket (cheap cloud-hosted file storage), then configure a CloudFront instance (Amazon's CDN) to talk to the S3 bucket as well as add HTTPS support and error page handling. Once everything is configured we have an automated deployment script."

According to you it would be best to host this on a Digital Ocean droplet. so I will get a 25gb for starters and send you the password.

--> My goal is to have to the full application running, with the api and the user functions enabled, but in such a way that I can develop several flavors of it over the next few months. So I need to know how to make a new flavor on the basis of an old one, how to edit it (which I can already do) and how to redeploy the modified version on the web.

--> If you think it is better to just install it and show me how to work it, that would be great. If you think it is better to walk me through the installation steps, that would be great as well. I should admit that I have never done anything with Python. If you think I will be unable to use this on my own, particularly because adminstering the server is too hard, that is obviously very valuable knowledge! I could also have the developers administer the server, but that would reduce the flexibility and I'd rather not.

**Comment by edwardsharp** [comment]
@Brian393 just sign up for digital ocean, add a CC (or add credits), add your SSH key, and then send me the password (do you use LastPass?). 

i'll setup the instance. probably going to use coreOS.

**Comment by edwardsharp** [comment]
@Brian393 also, where do you manage the DNS for ecotopia.today? probably via whatever registrar you used to register the domain? or probably your hosting provider (since the NS records for ecotopia.today point to webfaction.com)? it'd be handy if i could have access to that, too.

**Comment by Brian393** [comment]
Hi edward -

Thanks for this. I have to leave and go set up a show in another town but I
will try to set up the droplet, the ssh (I used to use it but I kinda
forgot) and the hosting info which is GoDaddy. But anyway, don't worry
about it. It all might have to wait till Sunday actually. I think there is
plenty of time.

Animation looks great!

BH

**Comment by edwardsharp** [comment]
i've created a repo with the docker-ized parts for running mapseed/api https://github.com/edwardsharp/ecotopia-today-mapseed

**Comment by Brian393** [comment]
Cool, I am leaving this place now so can't keep up with more but look
forward to going further on Sunday, thanks!
