### ISSUE TITLE
Push local master to remote

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#26]
My remote master is 50+ commits behind the local master. On github, the comparison says "ready to merge." I tried "git push origin/master" but that's not right, no such branch. The list of all branches is below. Do I run "git push remotes/origin/master"? Or ""git push remotes/origin/HEAD"?

brian@NewTerritories:~/Git/ecotopia-today$ git branch -a
  Brian-1
  Brian-a
  Brian-c
  Cascadia-1
  Cascadia-2
  brian-c
  lint-errors
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/gh-pages
  remotes/origin/lint-errors
  remotes/origin/master
  remotes/upstream/async-geoJSON
  remotes/upstream/gh-pages
  remotes/upstream/master

**Comment by edwardsharp** [comment]
@Brian393 first you need to checkout master. then fetch/pull from my branch (upstream/master) then you can push origin/master.

**Comment by edwardsharp** [comment]
@Brian393 also, this should work to add remote tracking to your master branch. if you are currently on the master branch: 

`git branch -u upstream/master`

or

`git branch -u upstream/master master`

EDIT: you want `origin/master` to push to your repo!

**Comment by edwardsharp** [comment]
looks like you got it pushed, closing.
